name: Release Obsidian Plugin
on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  node-setup:
    name: ⚙️ Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-cache
        id: cache-node-modules
        with:
          node-version: '20'
      - run: npm i
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  run-lint:
    name: ✅ Linter
    needs: node-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-cache
        id: cache-node-modules
        with:
          node-version: '20'

      - name: ✅ Run code style linter
        id: linter
        run: npm run lint

  release-plugin:
    name: 📦 Release Obsidian Plugin
    needs: run-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-cache
        id: cache-node-modules
        with:
          node-version: '20'
      
      - name: 📗 Build plugin
        id: build_plugin
        if: steps.cache-node-modules.outcome == 'success'
        run: npm run build

      - name: 📦 Create release
        uses: softprops/action-gh-release@v1
        if: steps.build_plugin.outcome == 'success' && contains(github.ref, 'refs/tags/')
        with:
          body: 'This release was generated automatically. Full details will be available soon'
          draft: true
          files: |
            main.js
            manifest.json
            styles.css